name: CI/CD

on:
  push:
    branches:
      - $default-branch
  workflow_dispatch:
    branches:
      - "*"

jobs:
  backend_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts"
      - name: Install Dependencies
        run: npm ci
      - name: Backend Tests
        run: npm run --prefix backend test:coverage
      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: backend-artifacts
          path: |
            backend/reports/rspec.xml
            backend/reports/coverage/cobertura-coverage.xml

  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts"
      - name: Install Dependencies
        run: npm ci
      - name: Build Frontend
        run: npm run --prefix app build
      - name: Upload Frontend Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: frontend-artifacts
          path: app/dist

  build_backend:
    needs: backend_tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts"
      - name: Install Dependencies
        run: npm ci
      - name: Build Backend
        run: npm run --prefix backend build
      - name: Upload Backend Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: backend-artifacts
          path: backend/dist

  deploy_backend:
    needs: build_backend
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy Backend
        run: echo "Deploy happens here, backend/dist already exists"

  deploy_frontend:
    needs: build_frontend
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy Frontend
        run: echo "Deploy happens here, app/dist already exists"
